---
title: ""
author: ""
date: ""
output: pdf_document
urlcolor: blue
---

Title: Lack of connectivity around stormwater ponds impacts Odonate abundance and species richness

Journal: Urban Ecosystems 

Authors: Richmond, Isabella C.*, Perron, Mary Ann C., Boyle, Sean B., & Pick, Frances R. 

(*) Department of Biology, 30 Marie Curie Private, University of Ottawa, Ottawa, Ontario K1N 6N5  
Department of Biology, 7141 Sherbrooke St. W., Concordia University, Montreal, QC, Canada H4B 1R6  
email: isabella.richmond@mail.concordia.ca, phone: 438-349-8064  

# Supplementary Information
This supplementary information file contains a study map with satellite imagery retrieved from Google Earth. The "qmap" function from ```ggmap``` was used to retrieve and visualize the satellite imagery (Kahle et al. 2019, v3.0.0 [CRAN](https://cran.r-project.org/web/packages/ggmap/ggmap.pdf)). ```ggplot2``` was used to visualize the study sites (Wickham et al. 2021, v3.3.3 [CRAN](https://cran.r-project.org/web/packages/ggplot2/index.html)). All associated code can be found at the paper's associated GitHub repository, [here](https://github.com/icrichmond/OdonataConnectivity). 

\newpage

```{r, echo=FALSE, message = FALSE, warning=FALSE, results = 'hide', fig.width = 7, fig.height=5}
#### Load Packages ####
libs <- c('sf', 'ggmap', 'ggplot2', 'dplyr', 'tibble', 'purrr')
lapply(libs, require, character.only = TRUE)

#### Study Sites ####
ponds <- readRDS("input/cleaned/CoorOttawa.rds")
ponds <- add_column(ponds, Group = "SWF")
ponds$Group[42:49] = "NAT"
# reproject data into WGS 84 for ease of interpretation
ponds <- st_transform(ponds, 4326)
# extract latitude and longitude 
ponds <- ponds %>%
  mutate(lat = unlist(map(ponds$geometry,1)),
         long = unlist(map(ponds$geometry,2)))
#### Study Site Figure ####
# Note: for this code to work you need a Google API with Geocoding and Maps Static enabled
# API: AIzaSyDlRF5BYeskCH7qWtq13WUV5ifG9Q1kT1c
register_google(key = "AIzaSyDlRF5BYeskCH7qWtq13WUV5ifG9Q1kT1c")
qmap(location = "Ottawa, Ontario", maptype = "satellite", source = "google") +
  geom_point(data = ponds, aes(x = lat, y = long, colour = Group), size = 4, shape = 20) + 
  scale_colour_manual(labels = c("Natural", "Stormwater"), 
                      values = c("burlywood4", "burlywood"))
```
\newline
Figure 1. Study area map. Study sites are grouped by pond type, n = 8 natural ponds and n = 41 stormwater facilities. Satellite imagery retrieved from Google Maps on August 3, 2021. Location geocode used was "Ottawa, Ontario". Geographic coordinate system is WGS84 (epsg: 4326).